### PR TITLE
Parse index.idx instead of scraping the html page

### PR DESCRIPTION
**Pull request by xoriath**
Instead of parsing the html page, use the CMSIS index file next to it to find the pack version and download path...

Ref https://arm-software.github.io/CMSIS_5/Pack/html/packIndexFile.html

### CODE REVIEW

**Review by mraardvark — APPROVED** [review]
Thanks :)

**Comment by brunob45** [comment]
Nice edit! I didn't know that index.idx file was available. 
But it looks like the lines 81-86 are the same as 90-95, is there something I'm missing?

**Comment by xoriath** [comment]
Nope, just my fat tired fingers :)

**Comment by xoriath** [comment]
@brunob45 any further comments?

**Comment by brunob45** [comment]
Just tested it, the script fails with the message:
`TypeError: expected str, bytes or os.PathLike object, not HTTPResponse` at the `gzip.GzipFile(...).read()` line.. Were you able to execute the script?

**Comment by xoriath** [comment]
Jupp, runs fine for me... What python version does PIO use? (I run it on python 3.9.2)

**Comment by xoriath** [comment]
Changed to not use the gz version of the file, just the raw xml... A bit more to download but shouldn't be very noticeable :)

**Comment by brunob45** [comment]
That I like, and it worked first try! I will merge shortly
P.S. don't use force-push, I would have "squash-merge" the commits anyway. It's just a bad practice.

**Pull request merged**
